-- ============================================================================
-- EP01 — Camada SILVER (modelo dimensional / esquema estrela)
-- ============================================================================
--
-- GRÃO DA FATO (RS1):
--   "Uma linha por PARTICIPAÇÃO de um Pokémon em um combate."
--   Cada combate gera DUAS linhas (uma por combatente). Escolhido porque reduz a
--   taxa de vitórias à média de uma única coluna booleana (venceu), eliminando o
--   risco de dupla contagem, ao custo de dobrar o volume da fato (100.000 linhas).
--
-- Este arquivo é IDEMPOTENTE: pode ser reexecutado. Ele recria o schema do zero;
-- a repopulação é feita pelo carregar.py, que roda este DDL e em seguida carrega.
--
-- Resumo das 6 decisões da seção 4.2 (justificativa completa no README):
--   1. Grão: participação (acima).
--   2. Diferença de velocidade (análise 5): gravada como MÉTRICA na fato
--      (diferenca_velocidade). Barato de guardar e deixa a análise 5 aditiva;
--      recalcular exigiria auto-join com o oponente a cada consulta.
--   3. Efetividade de tipos: tabela separada efetividade_tipo (324 linhas). A
--      análise 6/7 vira JOIN (RS7). Combinação de defensor com 2 tipos: tratada
--      na consulta/gold (os multiplicadores se multiplicam).
--   4. Oponente: dimensão papel (role-playing) — dim_pokemon referenciada 2x pela
--      fato (participante e oponente). dim_tipo também é role-playing.
--   5. Status (HP/ataque/defesa/velocidade): ficam em dim_pokemon (para a análise
--      2); a diferença de velocidade é duplicada como métrica na fato (análise 5).
--   6. Raridade: derivada na carga (categoria_raridade em dim_pokemon).
--
-- Observações:
--   - Só os 18 tipos reais entram em dim_tipo (stellar/unknown/shadow são filtrados
--     na carga — decisão documentada no README).
--   - Chaves naturais (num_pokedex, num_csv, id_tipo, num_geracao) são ATRIBUTOS,
--     nunca PK/FK (RS3): são o registro auditável da conciliação.
--   - Tipo primário e geração são DENORMALIZADOS em dim_pokemon (texto/inteiro)
--     para evitar snowflake (RS2): dimensão não referencia outra dimensão.
-- ============================================================================

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.schemata
        WHERE schema_name = 'silver'
    ) THEN
        CREATE SCHEMA silver;
    END IF;
END
$$;

-- Recriação limpa (idempotência) — ordem inversa das dependências
DROP TABLE IF EXISTS silver.fato_confronto   CASCADE;
DROP TABLE IF EXISTS silver.efetividade_tipo CASCADE;
DROP TABLE IF EXISTS silver.log_conciliacao  CASCADE;
DROP TABLE IF EXISTS silver.dim_pokemon      CASCADE;
DROP TABLE IF EXISTS silver.dim_tipo         CASCADE;
DROP TABLE IF EXISTS silver.dim_geracao      CASCADE;


-- ----------------------------------------------------------------------------
-- DIMENSÃO: Geração
-- ----------------------------------------------------------------------------
CREATE TABLE silver.dim_geracao (
    sk_geracao   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    num_geracao  INTEGER,          -- chave natural (1..6); NULL no membro especial
    nome         TEXT NOT NULL,    -- ex.: 'Geração I'
    regiao       TEXT              -- ex.: 'Kanto'
);


-- ----------------------------------------------------------------------------
-- DIMENSÃO: Tipo (18 reais + membro especial). Dimensão conformada, usada em
-- vários papéis: efetividade (atacante/defensor) e fato (participante/oponente).
-- ----------------------------------------------------------------------------
CREATE TABLE silver.dim_tipo (
    sk_tipo   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo   INTEGER,            -- chave natural da PokéAPI (1..18); NULL no especial
    nome      TEXT NOT NULL       -- ex.: 'fire'
);


-- ----------------------------------------------------------------------------
-- DIMENSÃO: Pokémon (~800 + membro especial). Dimensão papel na fato
-- (participante e oponente). Status vindos do pokemon.csv (base da simulação).
-- ----------------------------------------------------------------------------
CREATE TABLE silver.dim_pokemon (
    sk_pokemon         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- chaves naturais (auditoria — nunca PK/FK)
    num_pokedex        INTEGER,        -- id da PokéAPI; NULL quando não conciliado
    num_csv            INTEGER,        -- campo # do pokemon.csv
    -- identificação e classificação
    nome               TEXT NOT NULL,
    tipo_primario      TEXT,           -- denormalizado (evita snowflake)
    tipo_secundario    TEXT,           -- 'nenhum' quando ausente (conceito inaplicável)
    geracao            INTEGER,        -- denormalizado
    categoria_raridade TEXT,           -- derivado: Lendário / Mítico / Bebê / Comum
    is_legendary       BOOLEAN,
    is_mythical        BOOLEAN,
    is_baby            BOOLEAN,
    is_mega            BOOLEAN,
    -- habitat: distinguir 'não se aplica' (inaplicável, gerações pós FR/LG)
    -- de 'desconhecido' (dado ausente) — tratamentos diferentes (seção 1.4)
    habitat            TEXT,
    cor                TEXT,
    altura             INTEGER,
    peso               INTEGER,
    base_experience    INTEGER,
    capture_rate       INTEGER,
    base_happiness     INTEGER,
    -- atributos de status (fonte: pokemon.csv)
    hp                 INTEGER,
    ataque             INTEGER,
    defesa             INTEGER,
    sp_ataque          INTEGER,
    sp_defesa          INTEGER,
    velocidade         INTEGER
);


-- ----------------------------------------------------------------------------
-- EFETIVIDADE DE TIPOS (RS7): matriz 18x18 = 324 linhas materializada em SQL.
-- Multiplicador do tipo atacante contra o tipo defensor (0, 0.5, 1 ou 2).
-- O JSON lista só as exceções; as combinações não listadas valem 1 (preenchidas
-- na carga). Análises 6 e 7 são resolvidas por JOIN nesta tabela.
-- ----------------------------------------------------------------------------
CREATE TABLE silver.efetividade_tipo (
    sk_tipo_atacante  INTEGER NOT NULL REFERENCES silver.dim_tipo(sk_tipo),
    sk_tipo_defensor  INTEGER NOT NULL REFERENCES silver.dim_tipo(sk_tipo),
    multiplicador     NUMERIC(2,1) NOT NULL,   -- 0.0, 0.5, 1.0, 2.0
    PRIMARY KEY (sk_tipo_atacante, sk_tipo_defensor)
);


-- ----------------------------------------------------------------------------
-- FATO: Confronto (grão = participação). 100.000 linhas (2 por combate).
-- Toda FK aponta para uma linha existente (RS4/RS5): ausências usam o membro
-- especial (sk = -1) da dimensão correspondente, nunca NULL.
-- ----------------------------------------------------------------------------
CREATE TABLE silver.fato_confronto (
    sk_participacao       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_combate            INTEGER NOT NULL,   -- dimensão degenerada: liga as 2 participações
    -- dimensões papel
    sk_pokemon            INTEGER NOT NULL REFERENCES silver.dim_pokemon(sk_pokemon),
    sk_pokemon_oponente   INTEGER NOT NULL REFERENCES silver.dim_pokemon(sk_pokemon),
    sk_tipo_participante  INTEGER NOT NULL REFERENCES silver.dim_tipo(sk_tipo),
    sk_tipo_oponente      INTEGER NOT NULL REFERENCES silver.dim_tipo(sk_tipo),
    sk_geracao            INTEGER NOT NULL REFERENCES silver.dim_geracao(sk_geracao),
    -- métricas aditivas (RS6)
    venceu                SMALLINT NOT NULL CHECK (venceu IN (0, 1)),
    atacou_primeiro       SMALLINT NOT NULL CHECK (atacou_primeiro IN (0, 1)),
    diferenca_velocidade  INTEGER  NOT NULL   -- velocidade do participante - do oponente
);

-- Índices para acelerar as agregações do gold
CREATE INDEX idx_fato_pokemon    ON silver.fato_confronto (sk_pokemon);
CREATE INDEX idx_fato_tipo_part  ON silver.fato_confronto (sk_tipo_participante);
CREATE INDEX idx_fato_tipos      ON silver.fato_confronto (sk_tipo_participante, sk_tipo_oponente);


-- ----------------------------------------------------------------------------
-- LOG DE CONCILIAÇÃO (R4): artefato de auditoria. NÃO é fato nem dimensão e não
-- é consultado por nenhuma análise. Registra o resultado da conciliação CSV<->API.
-- ----------------------------------------------------------------------------
CREATE TABLE silver.log_conciliacao (
    num_csv      INTEGER,
    nome_csv     TEXT,
    conciliado   BOOLEAN NOT NULL,
    num_pokedex  INTEGER,       -- preenchido quando conciliado
    motivo       TEXT           -- razão quando NÃO conciliado (ex.: 'sem nome', 'nome não encontrado')
);


-- ============================================================================
-- MEMBROS ESPECIAIS (RS4) — sk = -1 representa a ausência explicitamente.
-- Inseridos no DDL para que a carga da fato sempre encontre uma FK válida.
--   - dim_pokemon(-1): destino do registro sem nome (#63) e de qualquer linha do
--     CSV não conciliada. As batalhas desses registros PERMANECEM no modelo
--     (R5: entram 50.000, permanecem 50.000), apontando para este membro.
--   - dim_tipo(-1): tipo desconhecido / secundário ausente.
--   - dim_geracao(-1): geração desconhecida.
-- ============================================================================
INSERT INTO silver.dim_geracao (sk_geracao, num_geracao, nome, regiao)
VALUES (-1, NULL, '(desconhecida)', NULL);

INSERT INTO silver.dim_tipo (sk_tipo, id_tipo, nome)
VALUES (-1, NULL, '(nenhum)');

INSERT INTO silver.dim_pokemon
    (sk_pokemon, num_pokedex, num_csv, nome, tipo_primario, tipo_secundario,
     geracao, categoria_raridade)
VALUES
    (-1, NULL, NULL, '(desconhecido)', NULL, 'nenhum', NULL, 'Desconhecido');